repos:
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/timothycrosley/isort
  rev: '5.12.0'
  hooks:
  - id: isort
    args: ["--profile", "black"]
    additional_dependencies:
      - toml
