input_data:
    content_column: 'content'
    label_column: 'label'
    max_length: 512
    input_data_path: './datasets/sample_data_multiclass.jsonl'
    stop_list_path: './datasets/sample_stoplist.txt'
    is_binary: False
    
input_model_and_tokenizer:
    model_and_tokenizer_dir: '../output/multiclass_model_and_tokenizer/'  
    
model:
    do_train: False

output_data:
    output_dir: '../output/multiclass_model/' 