name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black[jupyter] cython-lint flake8 isort pytest pytest-cov
          pip install --verbose --editable .

      - name: Check Python formatting with black
        run: |
          black --line-length 99 --diff --color .
          black --line-length=99 --check .

      - name: Check Cython formatting with cython-lint
        run: |
          cython-lint --max-line-length=99 --ignore=E741 .

      - name: Check import order with isort
        run: |
          isort --profile=black --line-length=99 --check .

      - name: Lint with flake8
        uses: py-actions/flake8@v1
        with:
          max-line-length: "99"
          exclude: "examples/*,fair_housing_guardrail/__init__.py"

      - name: Test with pytest
        run: |
          python -m pytest --pyargs tests/test_fair_housing_classification.py --cov=fair_housing_guardrail
